version: '3.9'

services:
  postgres:
    image: postgres:15.3
    container_name: postgres_ai_chat_app
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: pgadmin_ai_chat_app
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PGADMIN_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
